export const VOTING = {
    GET_ALL_CANDIDATES: "GET_ALL_CANDIDATES",
    CAST_YOUR_VOTES: "CAST_YOUR_VOTES",
    CHECK_ALREADY_VOTED: "CHECK_ALREADY_VOTED",
    GET_WINNER: "GET_WINNER",
    SET_VOTED_CANDIDATE: "SET_VOTED_CANDIDATE",
    SET_VOTE_TIME: "SET_VOTE_TIME",
    IS_CANDIDATE_ELIGIBLE: "IS_CANDIDATE_ELIGIBLE",
    SET_LOADING: "SET_LOADING",
    RESET: "RESET"
}